title: "Yonghwan's blog"
timezone: Asia/Seoul
url: "http://sio4.github.com"
feedurl: "http://feeds.feedburner.com/sio4-blog"
permalink: /blog/:year/:month/:day/:title
markdown: rdiscount

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories::title
